spring:
  application:
    name: first_wildfly
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      format_sql: true

server:
  port: 8452
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/baeldung.p12
    key-store-password: changeit
    key-alias: baeldung

trust:
  store: classpath:keystore/baeldung.p12
  store.password: changeit

logging:
  level:
    root: info
